export const Cities = [
	"All",
	"Digital First",
	"Atlanta, GA, USA",
	"Brisbane, QLD, AU",
	"Chattanooga, TN, USA",
	"Chicago, IL, USA",
	"Columbus, OH, USA",
	"Coromandel, WKO, NZ",
	"Denver, CO, USA",
	"Kalamazoo, MI, USA",
	"Los Angeles, CA, USA",
	"Madison, WI, USA",
	"Nashville, TN, USA",
	"New York, NY, USA",
	"Omaha, NE, USA",
	"Orlando, FL, USA",
	"Oxford, ENG, UK",
	"Philadelphia, PA, USA",
	"Savannah, GA, USA",
	"Washington, DC, USA",
	"Worcester, MA, USA"
] as const